services:
  mongo:
    image: mongo:6
    container_name: mongobis
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - ./stockage/mongo:/data/db
    # networks:
    #   - youtube_network
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
  postgres:
    image: postgres:14
    container_name: prefect_postgres
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - ./stockage/postgres:/var/lib/postgresql/data
    # networks:
    #   - youtube_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U prefect"]
    #   interval: 30s
    #   timeout: 10s
  #   #   retries: 5
  prefect:
    build:
      context: .
      dockerfile: Dockerfile_prefect
    container_name: prefect_orion
    restart: always
    depends_on:
      - postgres
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@postgres:5432/prefect"
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0

  agent:
    build:
      context: .
      dockerfile: Dockerfile_prefect
    container_name: prefect_agent
    restart: always
    depends_on:
      - prefect
    environment:
      PREFECT_API_URL: "http://prefect:4200/api"
    command: prefect worker start --pool my-docker-pool --type docker --work-queue "default"
  # prefect:
  #   image: prefecthq/prefect:3.4.11-python3.10
  #   container_name: prefect_orion
  #   restart: always
  #   depends_on:
  #     # postgres:
  #     #   condition: service_healthy
  #     - postgres
  #   environment:
  #     PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@postgres:5432/prefect"
  #   ports:
  #     - "4200:4200"
  #   # networks:
  #   #   - youtube_network
  #   command: prefect server start --host 0.0.0.0
  #   # healthcheck:
  #   #   test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 5
  # agent:
  #   image: prefecthq/prefect:3.4.11-python3.10
  #   container_name: prefect_agent
  #   restart: always
  #   depends_on:
  #     - prefect
  #     # prefect :
  #     #   condition: service_healthy
  #   environment:
  #     PREFECT_API_URL: "http://prefect:4200/api"
  #   # networks:
  #   #   - youtube_network
  #   command: prefect worker start --pool my-docker-pool --type docker --work-queue "default"
  # redis:
  #   image: redis:7-alpine
  #   container_name: youtube_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - youtube_network
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  # synchronisation:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_synchronisation
  #   container_name: synchronisation
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo
  #     - prefect
  #     # mongo:
  #     #   condition: service_healthy
  #     # prefect:
  #     #   condition: service_healthy
  #   environment:
  #     DEVELOPER_KEY: ${DEVELOPER_KEY}
  #     MONGO_USERNAME: ${MONGO_USERNAME}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #     # MONGO_HOST: mongo
  #     # MONGO_PORT: 27017
  #     MONGO_HOST: ${MONGO_HOST}
  #     MONGO_PORT: ${MONGO_PORT}
  #     MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
  #     PREFECT_API_URL: "http://prefect:4200/api"
  #   #   PYTHONPATH: "/app"
  #   # networks:
  #   #   - youtube_network
  #   volumes:
  #     - ./logs:/app/logs
  # streamlit:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_streamlit
  #   container_name: streamlit_app
  #   restart: unless-stopped
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #     prefect:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     # - mongo
  #     # - prefect
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     DEVELOPER_KEY: ${DEVELOPER_KEY}
  #     MONGO_USERNAME: ${MONGO_USERNAME}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #     MONGO_HOST: mongo
  #     MONGO_PORT: 27017
  #     # MONGO_HOST: 27017
  #     MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
  #     PREFECT_API_URL: "http://prefect:4200/api"
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     PYTHONPATH: "/app"
  #   networks:
  #     - youtube_network
  #   volumes:
  #     - ./logs:/app/logs
  #     - ./ressources:/app/ressources
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
#   nginx:
#     image: nginx:alpine
#     container_name: youtube_nginx
#     restart: unless-stopped
#     depends_on:
#       - streamlit
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     networks:
#       - youtube_network
# volumes:
#   mongo-data:
#     driver: local
#   postgres-data:
#     driver: local
#   redis-data:
#     driver: local

# networks:
#   youtube_network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16
# volumes:
#   mongo-data:
#   postgres-data:
