services:
  mongo:
    image: mongo:6
    container_name: mongobis
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - ./stockage/mongo:/data/db
  postgres:
    image: postgres:14
    container_name: prefect_postgres
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - ./stockage/postgres:/var/lib/postgresql/data
  prefect:
    build:
      context: .
      dockerfile: Dockerfile_prefect
    container_name: prefect_orion
    restart: always
    depends_on:
      - postgres
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@postgres:5432/prefect"
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0

  agent:
    build:
      context: .
      dockerfile: Dockerfile_prefect
    container_name: prefect_agent
    restart: always
    depends_on:
      - prefect
    environment:
      PREFECT_API_URL: "http://prefect:4200/api"
    command: prefect worker start --pool my-docker-pool --type docker --work-queue "default"
