services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db


  postgres:
      image: postgres:14
      container_name: prefect_postgres
      restart: always
      environment:
        POSTGRES_USER: prefect
        POSTGRES_PASSWORD: prefect
        POSTGRES_DB: prefect
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data


  prefect:
    image: prefecthq/prefect:3.4.11-python3.10
    container_name: prefect_orion
    restart: always
    depends_on:
      - postgres
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@postgres:5432/prefect"
    ports:
      - "4200:4200"
    command: prefect orion start --host 0.0.0.0

  agent:
    image: prefecthq/prefect:3.4.11-python3.10
    container_name: prefect_agent
    restart: always
    depends_on:
      - prefect
    environment:
      PREFECT_API_URL: "http://prefect:4200/api"
    command: prefect agent start --work-queue "default"

  synchronisation:
    build:
      context: .
      dockerfile: Dockerfile_synchronisation
    environment:
      DEVELOPER_KEY: ${DEVELOPER_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
      PREFECT_API_URL: ${PREFECT_API_URL}

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    environment:
      DEVELOPER_KEY: ${DEVELOPER_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
      PREFECT_API_URL: ${PREFECT_API_URL}

volumes:
  mongo-data:
  postgres-data: