version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  prefect-server :
    image: prefecthq/prefect:3-python3.10
    container_name: prefect-server
    ports:
      - "4200:4200"
      - "4201:4201"
    entrypoint: ["prefect", "server", "start"]
    command : ["--host", "0.0.0.0", "--port", "4200"]
    environment:
      PREFECT_API_URL: "http://localhost:4200/api"


volumes:
  mongo-data:
